
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile  # or Dockerfile if that's your actual filename
    container_name: cm-ecommerce-api
    ports: 
      - "5000:5000"
    volumes:
      - ./https:/https:ro
